### ISSUE TITLE
Division by zero while calculating usage percentage of swap

### ISSUE THREAD

**Issue by gongled** [essentialkaos/swptop#11]
### Bug report

**System info:**

* **Version used (`swptop -v`):** 0.4.0
* **OS (e.g. from `/etc/*-release`):** CentOS Linux release 7.4.1708 (Core)
* **Kernel (`uname -a`):** Linux example.com 3.10.0-693.17.1.el7.x86_64 UTC 2018 x86_64 GNU/Linux
* **Install tools:** n/a

**Steps to reproduce:**

1. Make sure that running processes are using swap memory.
2. Release swap
```
$ swapoff -a
```
I do not know why but `VmSwap` field in `/proc/<pid>/status` saves its state even if swap is disabled.

3. Run `swptop`.

**Expected behavior:**

Columns "Process" and "Overall" displays "n/a" or other mark which means that we are unable to calculate percentage of none swap.

**Actual behavior:**

`swptop` crashes.

**Additional info:**

```
$ swptop

------------------------------------------------------------------------------------------------------------------------
   PID |         USERNAME |     SWAP | COMMAND
------------------------------------------------------------------------------------------------------------------------
 15284 |            bash |     16KB | /bin/bash
 15265 |            bash |      4KB | /bin/bash
------------------------------------------------------------------------------------------------------------------------
panic: runtime error: index out of range

goroutine 1 [running]:
pkg.re/essentialkaos/ek.v9/fmtutil.formatPrettyFloat(0xc420016f80, 0x4, 0xc4201cbbc8, 0x1)
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/pkg.re/essentialkaos/ek.v9/fmtutil/fmtutil.go:249 +0x176
pkg.re/essentialkaos/ek.v9/fmtutil.PrettyNum(0x678ee0, 0xc420016f78, 0x678ee0, 0xc420016f78)
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/pkg.re/essentialkaos/ek.v9/fmtutil/fmtutil.go:48 +0xd4
pkg.re/essentialkaos/ek.v9/fmtutil.PrettyPerc(0x7ff0000000000000, 0xc420016f60, 0xc420016f74)
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/pkg.re/essentialkaos/ek.v9/fmtutil/fmtutil.go:62 +0x9c
main.printOverallInfo(0xc4200859e0, 0x2, 0x2)
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/github.com/essentialkaos/swptop/swptop.go:211 +0x167
main.printPrettyTop()
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/github.com/essentialkaos/swptop/swptop.go:184 +0x42a
main.main()
        /home/builder/rpmbuild/BUILD/swptop-0.4.0/src/github.com/essentialkaos/swptop/swptop.go:111 +0x151
```

**Comment by andyone** [comment]
I have released `swptop` and `ek` with the fix.
